('salesbyhour','Permission to view certain sales by hour reports.')
('batches','Create, edit, and delete Sales Batches.')
('pricechange','Permission to edit products via Item Maintenance.')
('delete_items','Delete products')
('ordering_edit','Permission to edit special orders.')
('cashierPerformance','View the cashier performance report.')
('overshorts','Permission to view cashier tender totals and enter actual counts. Not formally supported outside legacy yet.')
('admin','Gives the user permission to edit users, groups, and authorizations via the web interface.')
('memgen','Permission to create new member accounts')
('barcodes','View, edit, print, and delete shelftags.')
('editmembers','Edit members\' information')
('editcashiers','Edit cashiers via Admin => Cashier Management.')
('tenders','Create, edit, and delete tenders.')
('manage_likecodes','Edit like codes.')
('batches_audited','Create, edit, and view Sales Batches. See \"audited_pricechange\" for more info on the distinction that \"audited\" makes.')
('audited_pricechange','Gives access to edit products through Item Maintenance. Audited refers to the fact that the system emails buyers or department managers when users with this authorization actually edit products.')
('departments','Credit, edit, and delete department hierarchy')
