('salesbyhour','Permission to view certain sales by hour reports.')
('batches','Create, edit, and delete Sales Batches.')
('pricechange','Permission to edit products via Item Maintenance.')
('delete_items','Delete products')
('view_all_hours','Related to WFC-specific tools to track employee hours worked and PTO.')
('ordering_edit','Permission to edit special orders.')
('cashierPerformance','View the cashier performance report.')
('hours','Related to WFC-specific tools for tracking employee hours worked and PTO.')
('overshorts','Permission to view cashier tender totals and enter actual counts. Not formally supported outside legacy yet.')
('admin','Gives the user permission to edit users, groups, and authorizations via the web interface.')
('memgen','Permission to create new member accounts')
('projects','Relates to WFC-specific ticketing-system.')
('barcodes','View, edit, print, and delete shelftags.')
('produce','Relates to a very old WFC produce sales report.')
('staffar','Relates to WFC-specific tools for payroll deductions and A/R accounts.')
('mas90_journal','Relates to WFC-specific reports that export data for Sage MAS90.')
('editmembers_csc','A special authorization to edit just a subset of member information. Only applicable in WFC\'s legacy member management tool.')
('editmembers','Edit members\' information')
('editcashiers','Edit cashiers via Admin => Cashier Management.')
('evals','Relates to WFC-specific tool for tracking employee evaluations.')
('tenders','Create, edit, and delete tenders.')
('emailreporting','Related to a WFC-specific report of how often employees are checking their email.')
('manage_likecodes','Edit like codes.')
('backvoids','Void entire transactions via Fannie. Legacy feature not yet supported outside WFC.')
('batches_audited','Create, edit, and view Sales Batches. See \"audited_pricechange\" for more info on the distinction that \"audited\" makes.')
('audited_pricechange','Gives access to edit products through Item Maintenance. Audited refers to the fact that the system emails buyers or department managers when users with this authorization actually edit products.')
('edit_employees','Related to employee hours worked and PTO tracking. WFC specific.')
('upload_hours_data','Related to WFC-specific tools to track employee hours worked and PTO.')
('apptracking','Related to a legacy WFC job application tracking system.')
