# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "common/adodb5/*"
- "documentation/doxy/*"
- "fannie/legacy/*"
- "fannie/src/javascript/*"
- "fannie/src/fpdf/*"
- "fannie/src/Excel/*"
- "fannie/modules/plugins2.0/CoopDealsSigns/noauto/fonts/*"
- "tests/*"
- "fannie/item/deleteItem_WEFC_Toronto.php"
- "fannie/item/insertItem_WEFC_Toronto.php"
- "fannie/item/itemMaint_WEFC_Toronto.php"
- "fannie/item/itemMaint_WEFC_Toronto.php"
- "fannie/item/prodAllLanes_WEFC_Toronto.php"
- "fannie/item/prodFunction_WEFC_Toronto.php"
- "fannie/item/itemMaint_WEFC_Toronto.php"
- "fannie/item/updateItems_WEFC_Toronto.php"
- "fannie/item/import/loadWEFCTorontoProducts.php"
- "fannie/item/departments/import/loadWEFCTorontoDepts.php"
- "fannie/cron/members.sync.with.CiviCRM.php"
- "fannie/cron/members.update.from.CiviCRM.php"
