<?php

$CREATE['op.products'] = "
	CREATE TABLE `products` (
		  `upc` bigint(13) unsigned zerofill default NULL,
		  `description` varchar(30) default NULL,
		  `normal_price` double default NULL,
		  `pricemethod` smallint(6) default NULL,
		  `groupprice` double default NULL,
		  `quantity` smallint(6) default NULL,
		  `special_price` double default NULL,
		  `specialpricemethod` smallint(6) default NULL,
		  `specialgroupprice` double default NULL,
		  `specialquantity` smallint(6) default NULL,
		  `start_date` datetime default NULL,
		  `end_date` datetime default NULL,
		  `department` smallint(6) default NULL,
		  `size` varchar(9) default NULL,
		  `tax` smallint(6) default NULL,
		  `foodstamp` tinyint(4) default NULL,
		  `scale` tinyint(4) default NULL,
		  `scaleprice` tinyint(4) default 0 NULL,
		  `mixmatchcode` varchar(13) default NULL,
		  `modified` datetime default NULL,
		  `advertised` tinyint(4) default NULL,
		  `tareweight` double default NULL,
		  `discount` smallint(6) default NULL,
		  `discounttype` tinyint(4) default NULL,
		  `unitofmeasure` varchar(15) default NULL,
		  `wicable` smallint(6) default NULL,
		  `qttyEnforced` tinyint(4) default NULL,
		  `idEnforced` tinyint(4) default NULL,
		  `cost` double default 0 NULL,
		  `inUse` tinyint(4) default NULL,
		  `numflag` int(11) default '0',
		  `subdept` smallint(4) default NULL,
		  `deposit` double default NULL,
		  `local` int(11) default '0',
		  `id` int(11) NOT NULL auto_increment,
		  PRIMARY KEY  (`id`),
		  KEY `upc` (`upc`),
		  KEY `description` (`description`),
		  KEY `normal_price` (`normal_price`),
		  KEY `subdept` (`subdept`),
		  KEY `department` (`department`)
	)
";
if ($dbms == "MSSQL"){
	$CREATE['op.products'] = "
		CREATE TABLE [products] (
			[upc] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
			[description] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[normal_price] [money] NULL ,
			[pricemethod] [smallint] NULL ,
			[groupprice] [money] NULL ,
			[quantity] [smallint] NULL ,
			[special_price] [money] NULL ,
			[specialpricemethod] [smallint] NULL ,
			[specialgroupprice] [money] NULL ,
			[specialquantity] [smallint] NULL ,
			[start_date] [datetime] NULL ,
			[end_date] [datetime] NULL ,
			[department] [smallint] NOT NULL ,
			[size] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[tax] [smallint] NOT NULL ,
			[foodstamp] [bit] NOT NULL ,
			[Scale] [bit] NOT NULL ,
			[scaleprice] [tinyint] NULL ,
			[mixmatchcode] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[modified] [datetime] NULL ,
			[advertised] [bit] NOT NULL ,
			[tareweight] [float] NULL ,
			[discount] [smallint] NULL ,
			[discounttype] [tinyint] NULL ,
			[unitofmeasure] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[wicable] [smallint] NULL ,
			[qttyEnforced] [tinyint] NULL ,
			[idEnforced] [tinyint] NULL ,
			[cost] [money] NULL ,
			[inUse] [tinyint] NOT NULL ,		
			[numflag] [int] NULL ,
			[subdept] [smallint] NULL ,
			[deposit] [money] NULL ,
			[local] [int] NULL ,
			[id] [int] IDENTITY (1, 1) NOT NULL ,
			PRIMARY KEY ([id]) )
	";
}

?>
