Unstaged changes after reset:
M   fannie/classlib2.0/data/models/vmodels/EquityLiveBalanceModel.php
M   fannie/cron/Suspensions/deactivate.equity.php
M   fannie/cron/Suspensions/reactivate.equity.php
M   fannie/cron/memdates.fix.php
M   fannie/install/InstallIndexPage.php
M   fannie/install/InstallMembershipPage.php
M   fannie/install/sql/trans/deprecated/memIouToday.php
D   fannie/install/sql/trans/memIouToday.php
M   fannie/install/sql/trans/unpaid_ar_today.php
M   fannie/legacy/members/EOM_Reporting/equityDue1.php
M   fannie/legacy/members/EOM_Reporting/equityDue2.php
M   fannie/legacy/members/EOM_Reporting/inactivationsStock.php
M   fannie/legacy/members/EOM_Reporting/inactiveStockYTD.php
M   fannie/legacy/members/equity_letters/cards.php
M   fannie/legacy/members/equity_letters/due.php
M   fannie/legacy/members/equity_letters/index.php
M   fannie/legacy/members/equity_letters/mcards.php
M   fannie/legacy/members/equity_letters/newcards.php
M   fannie/legacy/members/equity_letters/pastdue.php
M   fannie/legacy/members/equity_letters/welcome.php
M   fannie/legacy/members/memAddress.php
M   fannie/legacy/members/stockOverdueReport.php
M   fannie/mem/modules/Equity.php
M   fannie/mem/statements/equity.php
M   fannie/reports/EquityAll/EquityAllReport.php
M   fannie/reports/Members/index.php
