<?php
/*******************************************************************************

    Copyright 2014 Whole Foods Co-op

    This file is part of CORE-POS.

    IT CORE is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    IT CORE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    in the file license.txt along with IT CORE; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*********************************************************************************/

/**
  @class ShelftagsModel
*/
class ShelftagsModel extends BasicModel
{

    protected $name = "shelftags";
    protected $preferred_db = 'op';

    protected $columns = array(
    'id' => array('type'=>'INT', 'primary_key'=>true),
    'upc' => array('type'=>'VARCHAR(13)', 'primary_key'=>true),
    'description' => array('type'=>'VARCHAR(30)'),
    'normal_price' => array('type'=>'MONEY'),
    'brand' => array('type'=>'VARCHAR(100)'),
    'sku' => array('type'=>'VARCHAR(13)'),
    'size' => array('type'=>'VARCHAR(50)'),
    'units' => array('type'=>'INT'),
    'vendor' => array('type'=>'VARCHAR(50)'),
    'pricePerUnit' => array('type'=>'VARCHAR(50)'),
    'count' => array('type'=>'TINYINT', 'default'=>1),
    'shelftagID' => array('type'=>'INT', 'increment'=>true, 'index'=>true),
    );

    public function doc()
    {
        return '
Use:
Data for generating shelf tag PDFs. id is used 
to segment sets into different PDF documents.
An id maps to a named ShelfTagQueue

Size relates to an indivdual product.
Units relates to a case. So a case of beer has 24
units, each with a size of 12 oz.

Count is used to print multiples of the same tag.
ShelftagID is used solely to track the order tags are
added so they can be printed in that sequence.
        ';
    }

    /**
      Build tag from the info generated by
      ProductsModel::getTagData
    */
    public function setData($info)
    {
        $this->description($info['description']);
        $this->normal_price($info['normal_price']);
        $this->brand($info['brand']);
        $this->sku($info['sku']);
        $this->size($info['size']);
        $this->units($info['units']);
        $this->vendor($info['vendor']);
        $this->pricePerUnit($info['pricePerUnit']);
    }
}

