name: Tests
on: [push, pull_request]
jobs:
    tests:
        strategy:
            matrix:
                operating-system: ['ubuntu-18.04']
                php-version: ['7.2']
                DB_DRIVER: ['pdo_mysql', 'mysqli']
        runs-on: ${{ matrix.operating-system }}
        steps:
            - uses: actions/checkout@v2
            - uses: nanasess/setup-php@master
              with:
                php-version: ${{ matrix.php-version }}
            - name: Start MySQL
              run: sudo systemctl start mysql.service
            - name: Init fannie config
              run: sh tests/fannie/gha-init.sh
              env:
                DB_DRIVER: ${{ matrix.DB_DRIVER }}
            - name: Init POS config
              run: sh tests/pos/gha-init.sh
              env:
                DB_DRIVER: ${{ matrix.DB_DRIVER }}
            - name: Use GHA version of parameters
              run: cp pos/is4c-nf/install/data/parameters.sql.gha pos/is4c-nf/install/data/parameters.sql
            - name: Validate config 1
              run: cat fannie/config.php
            - name: Validate config 2
              run: cat pos/is4c-nf/ini.json
            - name: Check database creation
              run: mysql -u root -proot -e 'SHOW DATABASES'
            - name: Clear composer.json
              run: rm composer.json
            - name: Clear composer.lock
              run: rm composer.lock
            - name: Init composer
              run: composer init --name corepos/ci-emv
            - name: Composer minimum install
              run: composer require johnkary/phpunit-speedtrap predis/predis
            - name: run tests
              run: sh .github/gha.sh
